### ISSUE TITLE
508/a11y: Footer links - contrast ratio is too low 

### ISSUE THREAD

**Issue by iamjolly** [gsa-oes/office-of-evaluation-sciences#334]
Footer links of with the teal (#2e9ac4) against light gray background (#f7f9fa) color have a 3.04:1 contrast ratio. 

To achieve a 4.5:1 or better ratio, use #237b96 for the link color in the footer. 
This will meet the [WCAG 2.1 AA (and Section 508) success criteria 1.4.3 Contrast (Minimum)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html).

Screenshot:
<img width="668" alt="Low color contrast of footer links as calculated by Chrome inspector" src="https://user-images.githubusercontent.com/1093423/130095974-2a1e514d-461b-4b23-aec9-d04c244e2525.png">

**Comment by alyssagalik** [comment]
Resolved issue - changed hyperlinks to a darker color
