### ISSUE TITLE
Updates do not work on mobile version of site

### ISSUE THREAD

**Issue by melodykramer** [gsa-oes/office-of-evaluation-sciences#45]
A friend tried to sign up for updates on her phone and said she could not access the page.

**Comment by dhcole** [comment]
@jeremiak did you happen to change anything with the form this morning? It looks like it's open so I'm not sure why this user would be blocked.

<img width="379" alt="screen shot 2015-09-16 at 1 37 42 pm" src="https://cloud.githubusercontent.com/assets/170641/9912946/219aa01a-5c78-11e5-8f87-155f8c36cda1.png">
