### ISSUE TITLE
Setting up new footer

### ISSUE THREAD

**Issue by mearley2013** [gsa-oes/office-of-evaluation-sciences#64]
Hi! We would like to add a footer that mirrors the design of the one on https://18f.gsa.gov/ that enables people to:
- Navigate to different pages on the website once they have scrolled to the bottom of the home page
- View relevant policies that apply to OES activities and website content
- Display various avenues for contacting OES (GSA press, Twitter, email)

We would like the footer to have the following layout:
- solid color section containing the footer, using the same blue used on the hero box in front of the kite photo (see https://federalist.fr.cloud.gov/preview/gsa-oes/office-of-evaluation-sciences/update-uswds/ as reference)
- on the far left, display both the OES logo (left) and GSA logo (right) side-by-side in their white versions (unless green OES logo works for contrast standards)
- on the far right, three columns with headers and corresponding links (I will input the specific pages to link to):

1. Column 1 (left): Header text - "Navigate"; # of links - 6
2. Column 2 (middle): Header text - "Policies"; # of links - 1
3. Column 3 (right): Header text - "Contact"; # of links - 3

**Comment by wslack** [comment]
@mearley2013 this was great!

**Comment by wslack** [comment]
@mearley2013 https://github.com/gsa-oes/office-of-evaluation-sciences/pull/65 is ready for your review!

**Comment by wslack** [comment]
Preview link: https://federalist.fr.cloud.gov/preview/gsa-oes/office-of-evaluation-sciences/add-new-footer/

**Comment by mearley2013** [comment]
@wslack @maya Thanks for making this work! One question - we want to swap the OES logo for a different file, but I don't understand how to replace the image link in this code. Can you tell me how to make this change?

**Comment by wslack** [comment]
@mearley2013 posted a comment about this in the PR. If you want to point at a different file, we'll need to make sure that the other file is in the repo first.

**Comment by mearley2013** [comment]
@wslack so I uploaded it, but I don't have the power (so it seems) to convert it from png to svg (currently uploaded as oes-logo-inverted-small.png). Though, this may not be relevant.

**Comment by wslack** [comment]
PNG > SVG conversion might be impossible; SVG files are mathematic instructions. do you have an  original SVG for that logo?
