### ISSUE TITLE
DAP not firing

### ISSUE THREAD

**Issue by mearley2013** [gsa-oes/office-of-evaluation-sciences#69]
Currently DAP code is not firing on all pages despite being included in the _includes/javascript code. seems to have been lost from the homepage layout/page layout structure (javascript not pulling?).

DAP team unsure how to troubleshoot because normally they don't work in github.

@wslack unsure how to fix, but all help appreciated!

**Comment by mearley2013** [comment]
Adding note to check the GA dashboard from the federal side bc I don't have federal access (it seems?)

**Comment by wslack** [comment]
I can't see GA for oes.gsa.gov.

What is *weird* is that the base.html file I was expecting isn't there, but it *used* to be there.

**Comment by mearley2013** [comment]
I'm just as confused (if not more confused) as you are

**Comment by wslack** [comment]
Ok, so site are built from templates.

We need a *base* template that applies to every page. That used to exist (or is shown in the site code for some pages, like the home page), but it needs to be readded explicitly.

**Comment by mearley2013** [comment]
Makes sense, thank you!

Let me know how/if I can be helpful with that!

**Comment by mearley2013** [comment]
@wslack Amira mentioned you were going to take a look at this over the weekend - checking in to see if you did, and either way what the next steps are for us to try to resolve this!

**Comment by wslack** [comment]
Yep, I know what needs to happen now; its just a matter of doing that coding.
