### ISSUE TITLE
Add code so that pictures load more quickly

### ISSUE THREAD

**Issue by mearley2013** [gsa-oes/office-of-evaluation-sciences#89]
@line47 We are looking to find a way to have our site images load more quickly, ideally through a code/process that requires minimal time burden/tediousness. The biggest issue area is the photos used in the project section, as they have a smaller thumbnail on the card displays that mirrors the identical-but-larger image on the individual project page.

Per our conversations so far, it seems there is a code currently in the works that could manage this process for the existing projects and future projects, but that it is not quite ready. Initiating this issue thread to monitor its progress and hopefully implement asap.

Thank you!

**Comment by line47** [comment]
Here was the responsive image generator to look into: 
https://github.com/mahnunchik/gulp-responsive
